swagger: '2.0'
info:
  description: 睿农通APP接口文档
  version: 1.0.0
  title: 睿农通APP接口文档
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: chendongdong@tr-ag.com
  license:
    name: Trust 1.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: rnt.dev.trust.com
basePath: /
tags:
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://rnt.dev.trust.com'
schemes:
  - http
paths:
  /user/registry:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: string
              msg:
                type: string
  /user/message:
    get:
      tags:
        - user
      summary: 手机有效验证
      description: ''
      operationId: phonecheck
      produces:
        - application/json
      parameters:
        - name: code
          in: query
          description: 验证手机号码
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: string
              msg:
                type: string
  /user/nickname:
    get:
      tags:
        - user
      summary: 昵称有效验证
      description: ''
      operationId: nicknamecheck
      produces:
        - application/json
      parameters:
        - name: nickname
          in: query
          description: 昵称
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: string
              msg:
                type: string
  /user/password:
    get:
      tags:
        - user
      summary: 密码有效性验证
      description: ''
      operationId: password
      produces:
        - application/json
      parameters:
        - name: password
          in: query
          description: 密码
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: string
              msg:
                type: string
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      produces:
        - application/json
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: string
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
  /user/logout:
    get:
      tags:
        - user
      summary: 帐号退出操作
      description: ''
      operationId: logoutUser
      produces:
        - application/json
      parameters:
        - name: userId
          in: query
          description: user id
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: string
              msg:
                type: string
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
    xml:
      name: User
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
